/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
import org.junit.jupiter.api.Test;

import java.io.*;
import java.lang.reflect.Type;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() throws FileNotFoundException {
        Gson gson=new Gson();
        Reader reader =new FileReader("../app/src/main/resources/recentquotes.json");

        Type collectionsType=new TypeToken<List<Quote>>(){}.getType();

        List<Quote> booksList= new Gson().fromJson(reader,collectionsType);


        Random random=new Random();
        int ranNum= random.nextInt((booksList.size()-1)+1);
        String str=booksList.get(ranNum).toString();

        assertEquals(str,booksList.get(ranNum).toString());

    }



        @Test void testApiReader() {
            String apiUrl = "http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en";
            String testQuote =  App.apiQuotes(apiUrl);
            assertTrue(testQuote != null);
        }
}
